name: petcode_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bottom_navy_bar: ^5.4.0
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.2.1
  cloud_firestore: ^0.13.7
  dio: ^3.0.10
  dots_indicator: ^1.2.0
  email_validator: ^1.0.5
  firebase_auth: ^0.16.1
  flutter_local_notifications: ^1.4.4+4
  flutter_secure_storage: ^3.3.3
  firebase_storage: ^3.1.6
  flutter_signin_button: ^1.0.0
  flutter_typeahead: ^1.8.7
  font_awesome_flutter: ^8.8.1
  intl_phone_number_input: ^0.4.6+2
  image_picker: ^0.6.7+4
  geolocator: ^5.3.2+2
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.28+1
  google_sign_in: ^4.5.1
  html: ^0.14.0+3
  outline_material_icons: ^0.1.1
  page_view_indicators: ^1.3.1
  pin_code_fields: ^3.1.2
  provider: ^4.3.1
  share: '>=0.6.4+3 <2.0.0'
  sliding_up_panel: ^1.0.2
  slimy_card: ^1.0.4
  uuid: ^2.2.0
  url_launcher: ^5.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
   - family: HeroIcons
     fonts:
       - asset: assets/icons/HeroIcons.ttf