name: petcode_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1+1
  bottom_navy_bar: ^5.6.0
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  circular_check_box: ^1.0.4
  cloud_firestore: ^0.14.3+1
  dio: ^3.0.10
  dots_indicator: ^1.2.0
  email_validator: ^1.0.6
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.2+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.1.0
  flutter_native_splash: ^0.1.9
  flutter_secure_storage: ^3.3.5
  flutter_spinkit: ^4.1.2+1
  flutter_typeahead: ^1.8.8
  font_awesome_flutter: ^8.10.0
  geocoding: ^1.0.5
  geolocator: ^6.1.8+1
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.0.6
  google_sign_in: ^4.5.6
  html: ^0.14.0+4
  image_picker: ^0.6.7+14
  intl_phone_number_input: ^0.5.2+2
  outline_material_icons: ^0.1.1
  page_view_indicators: ^1.4.0
  photo_view: ^0.10.3
  provider: ^4.3.2+2
  share: '>=0.6.5+4 <2.0.0'
  shared_preferences: ^0.5.12+4
  sliding_up_panel: ^1.0.2
  slimy_card: ^1.0.4
  url_launcher: ^5.7.10
  uuid: ^2.2.2



flutter_native_splash:
  image: assets/images/petcodesplashanim.gif
  color: "42a5f5"
  android_disable_fullscreen: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_background_image.png"
  adaptive_icon_foreground: "assets/icons/app_foreground_image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/navigation_images/
    - assets/images/onboarding/
    - assets/icons/custombluemarker.png
  fonts:
    - family: HeroIcons
      fonts:
        - asset: assets/icons/HeroIcons.ttf
    - family: HeroIcons2
      fonts:
        - asset: assets/icons/HeroIcons2.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700