/// Flutter icons HeroIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HeroIcons
///      fonts:
///       - asset: fonts/HeroIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HeroIcons {
  HeroIcons._();

  static const _kFontFam = 'HeroIcons';
  static const _kFontPkg = null;

  static const IconData icon_user_plus = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_video = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_view = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_x = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_x_circle = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_x_square = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_zoom_in = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_zoom_out = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_announcement = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_archive = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_down = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_left = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_right = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_up = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_at_symbol = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_book = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_bookmark = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_briefcase = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_browser = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_building = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_calander = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_incoming = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_outgoing = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_camera = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cart = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_chat = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_check_circle = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cheveron_down = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cheveron_left = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cheveron_right = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cheveron_up = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_clip = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_clipboard = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_clock = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_code = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cog = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_comment = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_compass = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_currency_dollar = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_dashboard = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_desktop = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_discount = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_download = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_duplicate = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_edit = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_emotion_happy = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_emotion_sad = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_exclamation = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_external_link = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_file = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_file_blank = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_file_minus = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_file_plus = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_film = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_filter = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_folder = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_folder_minus = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_folder_plus = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_globe = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_graph_bar = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_grid = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_group = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_hashtag = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_heart = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_help = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_home = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_image = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_inbox = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_information = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_key = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_link = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_location = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_lock_closed = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_lock_open = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mail = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_map = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_menu = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_microphone = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_minus = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_minus_circle = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_minus_square = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mobile = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_moon = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_more_horiz = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_music = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_news = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus_circle = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus_square = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_print = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_puzzle = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_refresh = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_repeat = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_rocket = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_server = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_speaker = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_star = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_store = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tablet = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tag = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_thumb_down = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_thumb_up = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trash = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trending_down = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trending_up = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trophy = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_upload = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user_check = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user_minus = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_clipboard_check = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
